//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



public partial class SmartPortalDataContext : Microsoft.SharePoint.Linq.DataContext {
	
	#region Extensibility Method Definitions
	partial void OnCreated();
	#endregion
	
	public SmartPortalDataContext(string requestUrl) : 
			base(requestUrl) {
		this.OnCreated();
	}
	
	/// <summary>
	/// Use the reports list to customize the queries that appear in the Content and Structure Tool views
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Content and Structure Reports")]
	public Microsoft.SharePoint.Linq.EntityList<ContentAndStructureReportsItem> ContentAndStructureReports {
		get {
			return this.GetList<ContentAndStructureReportsItem>("Content and Structure Reports");
		}
	}
	
	/// <summary>
	/// Sample customers list
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Customers")]
	public Microsoft.SharePoint.Linq.EntityList<CustomersContact> Customers {
		get {
			return this.GetList<CustomersContact>("Customers");
		}
	}
	
	/// <summary>
	/// Use the Contacts list for information about people that your team works with.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Customers CSOM")]
	public Microsoft.SharePoint.Linq.EntityList<CustomersCSOMContact> CustomersCSOM {
		get {
			return this.GetList<CustomersCSOMContact>("Customers CSOM");
		}
	}
	
	/// <summary>
	/// This system library was created by the Publishing feature to store documents that are used on pages in this site.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Documents")]
	public Microsoft.SharePoint.Linq.EntityList<Document> Documents {
		get {
			return this.GetList<Document>("Documents");
		}
	}
	
	/// <summary>
	/// This library contains administrator-approved form templates that were activated to this site collection.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Form Templates")]
	public Microsoft.SharePoint.Linq.EntityList<Item> FormTemplates {
		get {
			return this.GetList<Item>("Form Templates");
		}
	}
	
	/// <summary>
	/// This system library was created by the Publishing feature to store images that are used on pages in this site.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Images")]
	public Microsoft.SharePoint.Linq.EntityList<Item> Images {
		get {
			return this.GetList<Item>("Images");
		}
	}
	
	/// <summary>
	/// A list to track your favorite movies
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Movies")]
	public Microsoft.SharePoint.Linq.EntityList<Item> Movies {
		get {
			return this.GetList<Item>("Movies");
		}
	}
	
	/// <summary>
	/// This system library was created by the Publishing feature to store pages that are created in this site.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Pages")]
	public Microsoft.SharePoint.Linq.EntityList<Page> Pages {
		get {
			return this.GetList<Page>("Pages");
		}
	}
	
	/// <summary>
	/// Items in this list contain HTML or text content which can be inserted into web pages. If an item has automatic update selected, the content will be inserted into web pages as a read-only reference, and the content will update if the item is changed. If the item does not have automatic update selected, the content will be inserted as a copy in the web page, and the content will not update if the item is changed.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Reusable Content")]
	public Microsoft.SharePoint.Linq.EntityList<Item> ReusableContent {
		get {
			return this.GetList<Item>("Reusable Content");
		}
	}
	
	/// <summary>
	/// This system library was created by the Publishing Resources feature to store documents that are used throughout the site collection.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Site Collection Documents")]
	public Microsoft.SharePoint.Linq.EntityList<Document> SiteCollectionDocuments {
		get {
			return this.GetList<Document>("Site Collection Documents");
		}
	}
	
	/// <summary>
	/// This system library was created by the Publishing Resources feature to store images that are used throughout the site collection.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Site Collection Images")]
	public Microsoft.SharePoint.Linq.EntityList<Item> SiteCollectionImages {
		get {
			return this.GetList<Item>("Site Collection Images");
		}
	}
	
	/// <summary>
	/// Use the style library to store style sheets, such as CSS or XSL files. The style sheets in this gallery can be used by this site or any of its subsites.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Style Library")]
	public Microsoft.SharePoint.Linq.EntityList<Document> StyleLibrary {
		get {
			return this.GetList<Document>("Style Library");
		}
	}
	
	/// <summary>
	/// This system library was created by the Publishing feature to store workflow tasks that are created in this site.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Workflow Tasks")]
	public Microsoft.SharePoint.Linq.EntityList<Item> WorkflowTasks {
		get {
			return this.GetList<Item>("Workflow Tasks");
		}
	}
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Item", Id="0x01")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(ContentAndStructureReportsItem))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Folder))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Contact))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Document))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(MoviesListFieldsContentType))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(ReusableHTML))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(ReusableText))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Task))]
public partial class Item : Microsoft.SharePoint.Linq.ITrackEntityState, Microsoft.SharePoint.Linq.ITrackOriginalValues, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
	
	private System.Nullable<int> _id;
	
	private System.Nullable<int> _version;
	
	private string _path;
	
	private Microsoft.SharePoint.Linq.EntityState _entityState;
	
	private System.Collections.Generic.IDictionary<string, object> _originalValues;
	
	private string _title;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion

	Microsoft.SharePoint.Linq.EntityState Microsoft.SharePoint.Linq.ITrackEntityState.EntityState {
		get {
			return this._entityState;
		}
		set {
			if ((value != this._entityState)) {
				this._entityState = value;
			}
		}
	}

	System.Collections.Generic.IDictionary<string, object> Microsoft.SharePoint.Linq.ITrackOriginalValues.OriginalValues {
		get {
			if ((null == this._originalValues)) {
				this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
			}
			return this._originalValues;
		}
	}
	
	public Item() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ID", Storage="_id", ReadOnly=true, FieldType="Counter")]
	public System.Nullable<int> Id {
		get {
			return this._id;
		}
		set {
			if ((value != this._id)) {
				this.OnPropertyChanging("Id", this._id);
				this._id = value;
				this.OnPropertyChanged("Id");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="owshiddenversion", Storage="_version", ReadOnly=true, FieldType="Integer")]
	public System.Nullable<int> Version {
		get {
			return this._version;
		}
		set {
			if ((value != this._version)) {
				this.OnPropertyChanging("Version", this._version);
				this._version = value;
				this.OnPropertyChanged("Version");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileDirRef", Storage="_path", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
	public string Path {
		get {
			return this._path;
		}
		set {
			if ((value != this._path)) {
				this.OnPropertyChanging("Path", this._path);
				this._path = value;
				this.OnPropertyChanged("Path");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Title", Storage="_title", Required=true, FieldType="Text")]
	public virtual string Title {
		get {
			return this._title;
		}
		set {
			if ((value != this._title)) {
				this.OnPropertyChanging("Title", this._title);
				this._title = value;
				this.OnPropertyChanged("Title");
			}
		}
	}
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	protected virtual void OnPropertyChanged(string propertyName) {
		if ((null != this.PropertyChanged)) {
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	protected virtual void OnPropertyChanging(string propertyName, object value) {
		if ((null == this._originalValues)) {
			this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
		}
		if ((false == this._originalValues.ContainsKey(propertyName))) {
			this._originalValues.Add(propertyName, value);
		}
		if ((null != this.PropertyChanging)) {
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
}

/// <summary>
/// Create a new folder.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Folder", Id="0x0120")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(DocumentCollectionFolder))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(SummaryTask))]
public partial class Folder : Item {
	
	private string _name;
	
	private System.Nullable<int> _itemChildCountId;
	
	private string _itemChildCountItemChildCount;
	
	private System.Nullable<int> _folderChildCountId;
	
	private string _folderChildCountFolderChildCount;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Folder() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileLeafRef", Storage="_name", Required=true, FieldType="File")]
	public virtual string Name {
		get {
			return this._name;
		}
		set {
			if ((value != this._name)) {
				this.OnPropertyChanging("Name", this._name);
				this._name = value;
				this.OnPropertyChanged("Name");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Title {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Folder.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Folder.");
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ItemChildCount", Storage="_itemChildCountId", ReadOnly=true, FieldType="Lookup", IsLookupId=true)]
	public virtual System.Nullable<int> ItemChildCountId {
		get {
			return this._itemChildCountId;
		}
		set {
			if ((value != this._itemChildCountId)) {
				this.OnPropertyChanging("ItemChildCountId", this._itemChildCountId);
				this._itemChildCountId = value;
				this.OnPropertyChanged("ItemChildCountId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ItemChildCount", Storage="_itemChildCountItemChildCount", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
	public virtual string ItemChildCountItemChildCount {
		get {
			return this._itemChildCountItemChildCount;
		}
		set {
			if ((value != this._itemChildCountItemChildCount)) {
				this.OnPropertyChanging("ItemChildCountItemChildCount", this._itemChildCountItemChildCount);
				this._itemChildCountItemChildCount = value;
				this.OnPropertyChanged("ItemChildCountItemChildCount");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FolderChildCount", Storage="_folderChildCountId", ReadOnly=true, FieldType="Lookup", IsLookupId=true)]
	public virtual System.Nullable<int> FolderChildCountId {
		get {
			return this._folderChildCountId;
		}
		set {
			if ((value != this._folderChildCountId)) {
				this.OnPropertyChanging("FolderChildCountId", this._folderChildCountId);
				this._folderChildCountId = value;
				this.OnPropertyChanged("FolderChildCountId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FolderChildCount", Storage="_folderChildCountFolderChildCount", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
	public virtual string FolderChildCountFolderChildCount {
		get {
			return this._folderChildCountFolderChildCount;
		}
		set {
			if ((value != this._folderChildCountFolderChildCount)) {
				this.OnPropertyChanging("FolderChildCountFolderChildCount", this._folderChildCountFolderChildCount);
				this._folderChildCountFolderChildCount = value;
				this.OnPropertyChanged("FolderChildCountFolderChildCount");
			}
		}
	}
}

/// <summary>
/// Store information about a business or personal contact.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Contact", Id="0x0106")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(CustomersContact))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(CustomersCSOMContact))]
public partial class Contact : Item {
	
	private string _lastName;
	
	private string _lastName0;
	
	private string _firstName;
	
	private string _fullName;
	
	protected string _eMail;
	
	private string _company;
	
	private string _jobTitle;
	
	private string _businessPhone;
	
	private string _homePhone;
	
	private string _mobileNumber;
	
	private string _faxNumber;
	
	private string _address;
	
	private string _city;
	
	private string _stateProvince;
	
	private string _zIPPostalCode;
	
	private string _countryRegion;
	
	private string _webPage;
	
	private string _comments;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Contact() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="LinkTitle", Storage="_lastName", ReadOnly=true, FieldType="Computed")]
	public string LastName {
		get {
			return this._lastName;
		}
		set {
			if ((value != this._lastName)) {
				this.OnPropertyChanging("LastName", this._lastName);
				this._lastName = value;
				this.OnPropertyChanged("LastName");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="LinkTitleNoMenu", Storage="_lastName0", ReadOnly=true, FieldType="Computed")]
	public string LastName0 {
		get {
			return this._lastName0;
		}
		set {
			if ((value != this._lastName0)) {
				this.OnPropertyChanging("LastName0", this._lastName0);
				this._lastName0 = value;
				this.OnPropertyChanged("LastName0");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FirstName", Storage="_firstName", FieldType="Text")]
	public string FirstName {
		get {
			return this._firstName;
		}
		set {
			if ((value != this._firstName)) {
				this.OnPropertyChanging("FirstName", this._firstName);
				this._firstName = value;
				this.OnPropertyChanged("FirstName");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FullName", Storage="_fullName", FieldType="Text")]
	public string FullName {
		get {
			return this._fullName;
		}
		set {
			if ((value != this._fullName)) {
				this.OnPropertyChanging("FullName", this._fullName);
				this._fullName = value;
				this.OnPropertyChanged("FullName");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="EMail", Storage="_eMail", FieldType="Text")]
	public virtual string EMail {
		get {
			return this._eMail;
		}
		set {
			if ((value != this._eMail)) {
				this.OnPropertyChanging("EMail", this._eMail);
				this._eMail = value;
				this.OnPropertyChanged("EMail");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Company", Storage="_company", FieldType="Text")]
	public string Company {
		get {
			return this._company;
		}
		set {
			if ((value != this._company)) {
				this.OnPropertyChanging("Company", this._company);
				this._company = value;
				this.OnPropertyChanged("Company");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="JobTitle", Storage="_jobTitle", FieldType="Text")]
	public string JobTitle {
		get {
			return this._jobTitle;
		}
		set {
			if ((value != this._jobTitle)) {
				this.OnPropertyChanging("JobTitle", this._jobTitle);
				this._jobTitle = value;
				this.OnPropertyChanged("JobTitle");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WorkPhone", Storage="_businessPhone", FieldType="Text")]
	public string BusinessPhone {
		get {
			return this._businessPhone;
		}
		set {
			if ((value != this._businessPhone)) {
				this.OnPropertyChanging("BusinessPhone", this._businessPhone);
				this._businessPhone = value;
				this.OnPropertyChanged("BusinessPhone");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="HomePhone", Storage="_homePhone", FieldType="Text")]
	public string HomePhone {
		get {
			return this._homePhone;
		}
		set {
			if ((value != this._homePhone)) {
				this.OnPropertyChanging("HomePhone", this._homePhone);
				this._homePhone = value;
				this.OnPropertyChanged("HomePhone");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="CellPhone", Storage="_mobileNumber", FieldType="Text")]
	public string MobileNumber {
		get {
			return this._mobileNumber;
		}
		set {
			if ((value != this._mobileNumber)) {
				this.OnPropertyChanging("MobileNumber", this._mobileNumber);
				this._mobileNumber = value;
				this.OnPropertyChanged("MobileNumber");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WorkFax", Storage="_faxNumber", FieldType="Text")]
	public string FaxNumber {
		get {
			return this._faxNumber;
		}
		set {
			if ((value != this._faxNumber)) {
				this.OnPropertyChanging("FaxNumber", this._faxNumber);
				this._faxNumber = value;
				this.OnPropertyChanged("FaxNumber");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WorkAddress", Storage="_address", FieldType="Note")]
	public string Address {
		get {
			return this._address;
		}
		set {
			if ((value != this._address)) {
				this.OnPropertyChanging("Address", this._address);
				this._address = value;
				this.OnPropertyChanged("Address");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WorkCity", Storage="_city", FieldType="Text")]
	public string City {
		get {
			return this._city;
		}
		set {
			if ((value != this._city)) {
				this.OnPropertyChanging("City", this._city);
				this._city = value;
				this.OnPropertyChanged("City");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WorkState", Storage="_stateProvince", FieldType="Text")]
	public string StateProvince {
		get {
			return this._stateProvince;
		}
		set {
			if ((value != this._stateProvince)) {
				this.OnPropertyChanging("StateProvince", this._stateProvince);
				this._stateProvince = value;
				this.OnPropertyChanged("StateProvince");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WorkZip", Storage="_zIPPostalCode", FieldType="Text")]
	public string ZIPPostalCode {
		get {
			return this._zIPPostalCode;
		}
		set {
			if ((value != this._zIPPostalCode)) {
				this.OnPropertyChanging("ZIPPostalCode", this._zIPPostalCode);
				this._zIPPostalCode = value;
				this.OnPropertyChanged("ZIPPostalCode");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WorkCountry", Storage="_countryRegion", FieldType="Text")]
	public string CountryRegion {
		get {
			return this._countryRegion;
		}
		set {
			if ((value != this._countryRegion)) {
				this.OnPropertyChanging("CountryRegion", this._countryRegion);
				this._countryRegion = value;
				this.OnPropertyChanged("CountryRegion");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WebPage", Storage="_webPage", FieldType="Url")]
	public string WebPage {
		get {
			return this._webPage;
		}
		set {
			if ((value != this._webPage)) {
				this.OnPropertyChanging("WebPage", this._webPage);
				this._webPage = value;
				this.OnPropertyChanged("WebPage");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Comments", Storage="_comments", FieldType="Text")]
	public string Comments {
		get {
			return this._comments;
		}
		set {
			if ((value != this._comments)) {
				this.OnPropertyChanging("Comments", this._comments);
				this._comments = value;
				this.OnPropertyChanged("Comments");
			}
		}
	}
}

/// <summary>
/// Create a new document.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Document", Id="0x0101")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(RichMediaAsset))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(SystemPage))]
public partial class Document : Item {
	
	private string _name;
	
	private string _documentModifiedBy;
	
	private string _documentCreatedBy;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Document() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileLeafRef", Storage="_name", Required=true, FieldType="File")]
	public string Name {
		get {
			return this._name;
		}
		set {
			if ((value != this._name)) {
				this.OnPropertyChanging("Name", this._name);
				this._name = value;
				this.OnPropertyChanged("Name");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Modified_x0020_By", Storage="_documentModifiedBy", ReadOnly=true, FieldType="Text")]
	public string DocumentModifiedBy {
		get {
			return this._documentModifiedBy;
		}
		set {
			if ((value != this._documentModifiedBy)) {
				this.OnPropertyChanging("DocumentModifiedBy", this._documentModifiedBy);
				this._documentModifiedBy = value;
				this.OnPropertyChanged("DocumentModifiedBy");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Created_x0020_By", Storage="_documentCreatedBy", ReadOnly=true, FieldType="Text")]
	public string DocumentCreatedBy {
		get {
			return this._documentCreatedBy;
		}
		set {
			if ((value != this._documentCreatedBy)) {
				this.OnPropertyChanging("DocumentCreatedBy", this._documentCreatedBy);
				this._documentCreatedBy = value;
				this.OnPropertyChanged("DocumentCreatedBy");
			}
		}
	}
}

/// <summary>
/// Track a work item that you or your team needs to complete.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Task", Id="0x0108")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(WorkflowTasksTask))]
public partial class Task : Item {
	
	private System.Nullable<System.DateTime> _startDate;
	
	protected System.Nullable<System.DateTime> _dueDate;
	
	private System.Nullable<double> _complete;
	
	private string _body;
	
	private System.Nullable<Priority> _priority;
	
	protected System.Nullable<TaskStatus> _taskStatus;
	
	private System.Nullable<int> _assignedToId;
	
	private string _assignedTo;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Task() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="StartDate", Storage="_startDate", FieldType="DateTime")]
	public System.Nullable<System.DateTime> StartDate {
		get {
			return this._startDate;
		}
		set {
			if ((value != this._startDate)) {
				this.OnPropertyChanging("StartDate", this._startDate);
				this._startDate = value;
				this.OnPropertyChanged("StartDate");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="TaskDueDate", Storage="_dueDate", FieldType="DateTime")]
	public virtual System.Nullable<System.DateTime> DueDate {
		get {
			return this._dueDate;
		}
		set {
			if ((value != this._dueDate)) {
				this.OnPropertyChanging("DueDate", this._dueDate);
				this._dueDate = value;
				this.OnPropertyChanged("DueDate");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PercentComplete", Storage="_complete", FieldType="Number")]
	public System.Nullable<double> Complete {
		get {
			return this._complete;
		}
		set {
			if ((value != this._complete)) {
				this.OnPropertyChanging("Complete", this._complete);
				this._complete = value;
				this.OnPropertyChanged("Complete");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Body", Storage="_body", FieldType="Note")]
	public string Body {
		get {
			return this._body;
		}
		set {
			if ((value != this._body)) {
				this.OnPropertyChanging("Body", this._body);
				this._body = value;
				this.OnPropertyChanged("Body");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Priority", Storage="_priority", FieldType="Choice")]
	public System.Nullable<Priority> Priority {
		get {
			return this._priority;
		}
		set {
			if ((value != this._priority)) {
				this.OnPropertyChanging("Priority", this._priority);
				this._priority = value;
				this.OnPropertyChanged("Priority");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="TaskStatus", Storage="_taskStatus", FieldType="Choice")]
	public virtual System.Nullable<TaskStatus> TaskStatus {
		get {
			return this._taskStatus;
		}
		set {
			if ((value != this._taskStatus)) {
				this.OnPropertyChanging("TaskStatus", this._taskStatus);
				this._taskStatus = value;
				this.OnPropertyChanged("TaskStatus");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AssignedTo", Storage="_assignedToId", FieldType="User", IsLookupId=true)]
	public System.Nullable<int> AssignedToId {
		get {
			return this._assignedToId;
		}
		set {
			if ((value != this._assignedToId)) {
				this.OnPropertyChanging("AssignedToId", this._assignedToId);
				this._assignedToId = value;
				this.OnPropertyChanged("AssignedToId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AssignedTo", Storage="_assignedTo", ReadOnly=true, FieldType="User", IsLookupValue=true)]
	public string AssignedTo {
		get {
			return this._assignedTo;
		}
		set {
			if ((value != this._assignedTo)) {
				this.OnPropertyChanging("AssignedTo", this._assignedTo);
				this._assignedTo = value;
				this.OnPropertyChanged("AssignedTo");
			}
		}
	}
}

/// <summary>
/// Create a new Document Collection Folder
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Document Collection Folder", Id="0x0120D5")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(DocumentSet))]
public partial class DocumentCollectionFolder : Folder {
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public DocumentCollectionFolder() {
		this.OnCreated();
	}
}

/// <summary>
/// Group and describe related tasks that you or your team needs to complete.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Summary Task", Id="0x012004")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(WorkflowTasksSummaryTask))]
public partial class SummaryTask : Folder {
	
	private System.Nullable<double> _complete;
	
	private string _body;
	
	private System.Nullable<System.DateTime> _startDate;
	
	protected System.Nullable<System.DateTime> _dueDate;
	
	private System.Nullable<Priority> _priority;
	
	protected System.Nullable<TaskStatus> _taskStatus;
	
	private System.Nullable<int> _assignedToId;
	
	private string _assignedTo;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public SummaryTask() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PercentComplete", Storage="_complete", FieldType="Number")]
	public System.Nullable<double> Complete {
		get {
			return this._complete;
		}
		set {
			if ((value != this._complete)) {
				this.OnPropertyChanging("Complete", this._complete);
				this._complete = value;
				this.OnPropertyChanged("Complete");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Body", Storage="_body", FieldType="Note")]
	public string Body {
		get {
			return this._body;
		}
		set {
			if ((value != this._body)) {
				this.OnPropertyChanging("Body", this._body);
				this._body = value;
				this.OnPropertyChanged("Body");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="StartDate", Storage="_startDate", FieldType="DateTime")]
	public System.Nullable<System.DateTime> StartDate {
		get {
			return this._startDate;
		}
		set {
			if ((value != this._startDate)) {
				this.OnPropertyChanging("StartDate", this._startDate);
				this._startDate = value;
				this.OnPropertyChanged("StartDate");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="TaskDueDate", Storage="_dueDate", FieldType="DateTime")]
	public virtual System.Nullable<System.DateTime> DueDate {
		get {
			return this._dueDate;
		}
		set {
			if ((value != this._dueDate)) {
				this.OnPropertyChanging("DueDate", this._dueDate);
				this._dueDate = value;
				this.OnPropertyChanged("DueDate");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Priority", Storage="_priority", FieldType="Choice")]
	public System.Nullable<Priority> Priority {
		get {
			return this._priority;
		}
		set {
			if ((value != this._priority)) {
				this.OnPropertyChanging("Priority", this._priority);
				this._priority = value;
				this.OnPropertyChanged("Priority");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="TaskStatus", Storage="_taskStatus", FieldType="Choice")]
	public virtual System.Nullable<TaskStatus> TaskStatus {
		get {
			return this._taskStatus;
		}
		set {
			if ((value != this._taskStatus)) {
				this.OnPropertyChanging("TaskStatus", this._taskStatus);
				this._taskStatus = value;
				this.OnPropertyChanged("TaskStatus");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AssignedTo", Storage="_assignedToId", FieldType="User", IsLookupId=true)]
	public System.Nullable<int> AssignedToId {
		get {
			return this._assignedToId;
		}
		set {
			if ((value != this._assignedToId)) {
				this.OnPropertyChanging("AssignedToId", this._assignedToId);
				this._assignedToId = value;
				this.OnPropertyChanged("AssignedToId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AssignedTo", Storage="_assignedTo", ReadOnly=true, FieldType="User", IsLookupValue=true)]
	public string AssignedTo {
		get {
			return this._assignedTo;
		}
		set {
			if ((value != this._assignedTo)) {
				this.OnPropertyChanging("AssignedTo", this._assignedTo);
				this._assignedTo = value;
				this.OnPropertyChanged("AssignedTo");
			}
		}
	}
}

/// <summary>
/// Create a document set when you want to manage multiple documents as a single work product.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Document Set", Id="0x0120D520")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(ImagesVideo))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(SiteCollectionImagesVideo))]
public partial class DocumentSet : DocumentCollectionFolder {
	
	private string _description;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public DocumentSet() {
		this.OnCreated();
	}
	
	/// <summary>
	/// A description of the Document Set
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DocumentSetDescription", Storage="_description", FieldType="Note")]
	public virtual string Description {
		get {
			return this._description;
		}
		set {
			if ((value != this._description)) {
				this.OnPropertyChanging("Description", this._description);
				this._description = value;
				this.OnPropertyChanged("Description");
			}
		}
	}
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Item", Id="0x01", List="Content and Structure Reports")]
public partial class ContentAndStructureReportsItem : Item {
	
	private string _resourceId;
	
	private string _resourceId0;
	
	private string _cAMLListType;
	
	private string _cAMLQuery;
	
	private string _reportDescription;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public ContentAndStructureReportsItem() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0024_Resources_x003a_cmscore_x", Storage="_resourceId", FieldType="Text")]
	public string ResourceId {
		get {
			return this._resourceId;
		}
		set {
			if ((value != this._resourceId)) {
				this.OnPropertyChanging("ResourceId", this._resourceId);
				this._resourceId = value;
				this.OnPropertyChanged("ResourceId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0024_Resources_x003a_cmscore_x0", Storage="_resourceId0", FieldType="Text")]
	public string ResourceId0 {
		get {
			return this._resourceId0;
		}
		set {
			if ((value != this._resourceId0)) {
				this.OnPropertyChanging("ResourceId0", this._resourceId0);
				this._resourceId0 = value;
				this.OnPropertyChanged("ResourceId0");
			}
		}
	}
	
	/// <summary>
	/// Type the name of the list template for the CAML list type, or leave blank to search document library template
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0024_Resources_x003a_cmscore_x1", Storage="_cAMLListType", FieldType="Text")]
	public string CAMLListType {
		get {
			return this._cAMLListType;
		}
		set {
			if ((value != this._cAMLListType)) {
				this.OnPropertyChanging("CAMLListType", this._cAMLListType);
				this._cAMLListType = value;
				this.OnPropertyChanged("CAMLListType");
			}
		}
	}
	
	/// <summary>
	/// Type the CAML markup for the report query
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0024_Resources_x003a_cmscore_x2", Storage="_cAMLQuery", Required=true, FieldType="Text")]
	public string CAMLQuery {
		get {
			return this._cAMLQuery;
		}
		set {
			if ((value != this._cAMLQuery)) {
				this.OnPropertyChanging("CAMLQuery", this._cAMLQuery);
				this._cAMLQuery = value;
				this.OnPropertyChanged("CAMLQuery");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Report_x0020_Description", Storage="_reportDescription", FieldType="Text")]
	public string ReportDescription {
		get {
			return this._reportDescription;
		}
		set {
			if ((value != this._reportDescription)) {
				this.OnPropertyChanging("ReportDescription", this._reportDescription);
				this._reportDescription = value;
				this.OnPropertyChanged("ReportDescription");
			}
		}
	}
}

[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Reusable HTML", Id="0x01002CF74A4DAE39480396EEA7A4BA2BE5FB")]
public partial class ReusableHTML : Item {
	
	private string _title0;
	
	private string _comments;
	
	private System.Nullable<bool> _automaticUpdate;
	
	private System.Nullable<bool> _showInDropDownMenu;
	
	private System.Nullable<ContentCategory> _contentCategory;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public ReusableHTML() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="LinkTitle", Storage="_title0", ReadOnly=true, Required=true, FieldType="Computed")]
	public string Title0 {
		get {
			return this._title0;
		}
		set {
			if ((value != this._title0)) {
				this.OnPropertyChanging("Title0", this._title0);
				this._title0 = value;
				this.OnPropertyChanged("Title0");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Comments", Storage="_comments", FieldType="Text")]
	public string Comments {
		get {
			return this._comments;
		}
		set {
			if ((value != this._comments)) {
				this.OnPropertyChanging("Comments", this._comments);
				this._comments = value;
				this.OnPropertyChanged("Comments");
			}
		}
	}
	
	/// <summary>
	/// If this option is selected, the content of this list item will be inserted into web pages as a read-only reference. New versions of this item will automatically appear in the web pages. If the option is not selected, the content of this list item will be inserted into web pages as a copy that page authors can then modify. New versions of this item will not appear in the web pages. Any change to this setting will not affect existing web pages that are using this item.
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AutomaticUpdate", Storage="_automaticUpdate", FieldType="Boolean")]
	public System.Nullable<bool> AutomaticUpdate {
		get {
			return this._automaticUpdate;
		}
		set {
			if ((value != this._automaticUpdate)) {
				this.OnPropertyChanging("AutomaticUpdate", this._automaticUpdate);
				this._automaticUpdate = value;
				this.OnPropertyChanged("AutomaticUpdate");
			}
		}
	}
	
	/// <summary>
	/// Select this option if you want this reusable content item to appear in a drop-down menu available during page editing. This will offer authors a quick way to add this item to a page.
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ShowInRibbon", Storage="_showInDropDownMenu", FieldType="Boolean")]
	public System.Nullable<bool> ShowInDropDownMenu {
		get {
			return this._showInDropDownMenu;
		}
		set {
			if ((value != this._showInDropDownMenu)) {
				this.OnPropertyChanging("ShowInDropDownMenu", this._showInDropDownMenu);
				this._showInDropDownMenu = value;
				this.OnPropertyChanged("ShowInDropDownMenu");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ContentCategory", Storage="_contentCategory", FieldType="Choice")]
	public System.Nullable<ContentCategory> ContentCategory {
		get {
			return this._contentCategory;
		}
		set {
			if ((value != this._contentCategory)) {
				this.OnPropertyChanging("ContentCategory", this._contentCategory);
				this._contentCategory = value;
				this.OnPropertyChanged("ContentCategory");
			}
		}
	}
}

[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Reusable Text", Id="0x01004D5A79BAFA4A4576B79C56FF3D0D662D")]
public partial class ReusableText : Item {
	
	private string _title0;
	
	private string _comments;
	
	private System.Nullable<bool> _automaticUpdate;
	
	private System.Nullable<bool> _showInDropDownMenu;
	
	private string _reusableText0;
	
	private System.Nullable<ContentCategory> _contentCategory;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public ReusableText() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="LinkTitle", Storage="_title0", ReadOnly=true, FieldType="Computed")]
	public string Title0 {
		get {
			return this._title0;
		}
		set {
			if ((value != this._title0)) {
				this.OnPropertyChanging("Title0", this._title0);
				this._title0 = value;
				this.OnPropertyChanged("Title0");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Comments", Storage="_comments", FieldType="Text")]
	public string Comments {
		get {
			return this._comments;
		}
		set {
			if ((value != this._comments)) {
				this.OnPropertyChanging("Comments", this._comments);
				this._comments = value;
				this.OnPropertyChanged("Comments");
			}
		}
	}
	
	/// <summary>
	/// If this option is selected, the content of this list item will be inserted into web pages as a read-only reference. New versions of this item will automatically appear in the web pages. If the option is not selected, the content of this list item will be inserted into web pages as a copy that page authors can then modify. New versions of this item will not appear in the web pages. Any change to this setting will not affect existing web pages that are using this item.
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AutomaticUpdate", Storage="_automaticUpdate", FieldType="Boolean")]
	public System.Nullable<bool> AutomaticUpdate {
		get {
			return this._automaticUpdate;
		}
		set {
			if ((value != this._automaticUpdate)) {
				this.OnPropertyChanging("AutomaticUpdate", this._automaticUpdate);
				this._automaticUpdate = value;
				this.OnPropertyChanged("AutomaticUpdate");
			}
		}
	}
	
	/// <summary>
	/// Select this option if you want this reusable content item to appear in a drop-down menu available during page editing. This will offer authors a quick way to add this item to a page.
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ShowInRibbon", Storage="_showInDropDownMenu", FieldType="Boolean")]
	public System.Nullable<bool> ShowInDropDownMenu {
		get {
			return this._showInDropDownMenu;
		}
		set {
			if ((value != this._showInDropDownMenu)) {
				this.OnPropertyChanging("ShowInDropDownMenu", this._showInDropDownMenu);
				this._showInDropDownMenu = value;
				this.OnPropertyChanged("ShowInDropDownMenu");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ReusableText", Storage="_reusableText0", FieldType="Note")]
	public string ReusableText0 {
		get {
			return this._reusableText0;
		}
		set {
			if ((value != this._reusableText0)) {
				this.OnPropertyChanging("ReusableText0", this._reusableText0);
				this._reusableText0 = value;
				this.OnPropertyChanged("ReusableText0");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ContentCategory", Storage="_contentCategory", FieldType="Choice")]
	public System.Nullable<ContentCategory> ContentCategory {
		get {
			return this._contentCategory;
		}
		set {
			if ((value != this._contentCategory)) {
				this.OnPropertyChanging("ContentCategory", this._contentCategory);
				this._contentCategory = value;
				this.OnPropertyChanged("ContentCategory");
			}
		}
	}
}

/// <summary>
/// Store information about a business or personal contact.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Contact", Id="0x0106", List="Customers")]
public partial class CustomersContact : Contact {
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public CustomersContact() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Email", Storage="_eMail", FieldType="Text")]
	public override string EMail {
		get {
			return this._eMail;
		}
		set {
			if ((value != this._eMail)) {
				this.OnPropertyChanging("EMail", this._eMail);
				this._eMail = value;
				this.OnPropertyChanged("EMail");
			}
		}
	}
}

/// <summary>
/// Store information about a business or personal contact.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Contact", Id="0x0106", List="Customers CSOM")]
public partial class CustomersCSOMContact : Contact {
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public CustomersCSOMContact() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Email", Storage="_eMail", FieldType="Text")]
	public override string EMail {
		get {
			return this._eMail;
		}
		set {
			if ((value != this._eMail)) {
				this.OnPropertyChanging("EMail", this._eMail);
				this._eMail = value;
				this.OnPropertyChanged("EMail");
			}
		}
	}
}

/// <summary>
/// Upload an asset.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Rich Media Asset", Id="0x0101009148F5A04DDD49CBA7127AADA5FB792B")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Image))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Audio))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(VideoRendition))]
public partial class RichMediaAsset : Document {
	
	private string _preview;
	
	private string _keywords;
	
	private string _thumbnailPreview;
	
	private System.Nullable<int> _pictureWidth;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public RichMediaAsset() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PreviewOnForm", Storage="_preview", FieldType="Computed")]
	public string Preview {
		get {
			return this._preview;
		}
		set {
			if ((value != this._preview)) {
				this.OnPropertyChanging("Preview", this._preview);
				this._preview = value;
				this.OnPropertyChanged("Preview");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Keywords", Storage="_keywords", FieldType="Note")]
	public string Keywords {
		get {
			return this._keywords;
		}
		set {
			if ((value != this._keywords)) {
				this.OnPropertyChanging("Keywords", this._keywords);
				this._keywords = value;
				this.OnPropertyChanged("Keywords");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ThumbnailOnForm", Storage="_thumbnailPreview", FieldType="Computed")]
	public string ThumbnailPreview {
		get {
			return this._thumbnailPreview;
		}
		set {
			if ((value != this._thumbnailPreview)) {
				this.OnPropertyChanging("ThumbnailPreview", this._thumbnailPreview);
				this._thumbnailPreview = value;
				this.OnPropertyChanged("ThumbnailPreview");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ImageWidth", Storage="_pictureWidth", ReadOnly=true, FieldType="Integer")]
	public System.Nullable<int> PictureWidth {
		get {
			return this._pictureWidth;
		}
		set {
			if ((value != this._pictureWidth)) {
				this.OnPropertyChanging("PictureWidth", this._pictureWidth);
				this._pictureWidth = value;
				this.OnPropertyChanged("PictureWidth");
			}
		}
	}
}

/// <summary>
/// System Page is a system content type template created by the Publishing Resources feature, and it cannot be modified. To add columns to the Pages library, update the Page content type template.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="System Page", Id="0x010100C568DB52D9D0A14D9B2FDCC96666E9F2")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Page))]
public partial class SystemPage : Document {
	
	private string _comments;
	
	private string _contactEMailAddress;
	
	private string _contactName;
	
	private string _contactPicture;
	
	private string _pageLayout;
	
	private System.Nullable<bool> _hidePhysicalURLsFromSearch;
	
	private System.Nullable<int> _contactId;
	
	private string _contact;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public SystemPage() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Comments", Storage="_comments", FieldType="Text")]
	public string Comments {
		get {
			return this._comments;
		}
		set {
			if ((value != this._comments)) {
				this.OnPropertyChanging("Comments", this._comments);
				this._comments = value;
				this.OnPropertyChanged("Comments");
			}
		}
	}
	
	/// <summary>
	/// Contact E-mail Address is a site column created by the Publishing feature. It is used on the Page Content Type as the e-mail address of the person or group who is the contact person for the page.
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PublishingContactEmail", Storage="_contactEMailAddress", FieldType="Text")]
	public string ContactEMailAddress {
		get {
			return this._contactEMailAddress;
		}
		set {
			if ((value != this._contactEMailAddress)) {
				this.OnPropertyChanging("ContactEMailAddress", this._contactEMailAddress);
				this._contactEMailAddress = value;
				this.OnPropertyChanged("ContactEMailAddress");
			}
		}
	}
	
	/// <summary>
	/// Contact Name is a site column created by the Publishing feature. It is used on the Page Content Type as the name of the person or group who is the contact person for the page.
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PublishingContactName", Storage="_contactName", FieldType="Text")]
	public string ContactName {
		get {
			return this._contactName;
		}
		set {
			if ((value != this._contactName)) {
				this.OnPropertyChanging("ContactName", this._contactName);
				this._contactName = value;
				this.OnPropertyChanged("ContactName");
			}
		}
	}
	
	/// <summary>
	/// Contact Picture is a site column created by the Publishing feature. It is used on the Page Content Type as the picture of the user or group who is the contact person for the page.
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PublishingContactPicture", Storage="_contactPicture", FieldType="Url")]
	public string ContactPicture {
		get {
			return this._contactPicture;
		}
		set {
			if ((value != this._contactPicture)) {
				this.OnPropertyChanging("ContactPicture", this._contactPicture);
				this._contactPicture = value;
				this.OnPropertyChanged("ContactPicture");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PublishingPageLayout", Storage="_pageLayout", ReadOnly=true, FieldType="Url")]
	public string PageLayout {
		get {
			return this._pageLayout;
		}
		set {
			if ((value != this._pageLayout)) {
				this.OnPropertyChanging("PageLayout", this._pageLayout);
				this._pageLayout = value;
				this.OnPropertyChanged("PageLayout");
			}
		}
	}
	
	/// <summary>
	/// If checked, the physical URL of this page will not appear in search results. Friendly URLs assigned to this page will always appear.
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PublishingIsFurlPage", Storage="_hidePhysicalURLsFromSearch", FieldType="Boolean")]
	public System.Nullable<bool> HidePhysicalURLsFromSearch {
		get {
			return this._hidePhysicalURLsFromSearch;
		}
		set {
			if ((value != this._hidePhysicalURLsFromSearch)) {
				this.OnPropertyChanging("HidePhysicalURLsFromSearch", this._hidePhysicalURLsFromSearch);
				this._hidePhysicalURLsFromSearch = value;
				this.OnPropertyChanged("HidePhysicalURLsFromSearch");
			}
		}
	}
	
	/// <summary>
	/// Contact is a site column created by the Publishing feature. It is used on the Page Content Type as the person or group who is the contact person for the page.
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PublishingContact", Storage="_contactId", FieldType="User", IsLookupId=true)]
	public System.Nullable<int> ContactId {
		get {
			return this._contactId;
		}
		set {
			if ((value != this._contactId)) {
				this.OnPropertyChanging("ContactId", this._contactId);
				this._contactId = value;
				this.OnPropertyChanged("ContactId");
			}
		}
	}
	
	/// <summary>
	/// Contact is a site column created by the Publishing feature. It is used on the Page Content Type as the person or group who is the contact person for the page.
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PublishingContact", Storage="_contact", ReadOnly=true, FieldType="User", IsLookupValue=true)]
	public string Contact {
		get {
			return this._contact;
		}
		set {
			if ((value != this._contact)) {
				this.OnPropertyChanging("Contact", this._contact);
				this._contact = value;
				this.OnPropertyChanged("Contact");
			}
		}
	}
}

/// <summary>
/// Track a work item that you or your team needs to complete.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Task", Id="0x0108", List="Workflow Tasks")]
public partial class WorkflowTasksTask : Task {
	
	private Microsoft.SharePoint.Linq.EntitySet<Item> _predecessors;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public WorkflowTasksTask() {
		this._predecessors = new Microsoft.SharePoint.Linq.EntitySet<Item>();
		this._predecessors.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item>>(this.OnPredecessorsSync);
		this._predecessors.OnChanged += new System.EventHandler(this.OnPredecessorsChanged);
		this._predecessors.OnChanging += new System.EventHandler(this.OnPredecessorsChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DueDate", Storage="_dueDate", FieldType="DateTime")]
	public override System.Nullable<System.DateTime> DueDate {
		get {
			return this._dueDate;
		}
		set {
			if ((value != this._dueDate)) {
				this.OnPropertyChanging("DueDate", this._dueDate);
				this._dueDate = value;
				this.OnPropertyChanged("DueDate");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Status", Storage="_taskStatus", FieldType="Choice")]
	public override System.Nullable<TaskStatus> TaskStatus {
		get {
			return this._taskStatus;
		}
		set {
			if ((value != this._taskStatus)) {
				this.OnPropertyChanging("TaskStatus", this._taskStatus);
				this._taskStatus = value;
				this.OnPropertyChanged("TaskStatus");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Predecessors", Storage="_predecessors", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Multi, List="Workflow Tasks")]
	public Microsoft.SharePoint.Linq.EntitySet<Item> Predecessors {
		get {
			return this._predecessors;
		}
		set {
			this._predecessors.Assign(value);
		}
	}
	
	private void OnPredecessorsChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Predecessors", this._predecessors.Clone());
	}
	
	private void OnPredecessorsChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Predecessors");
	}
	
	private void OnPredecessorsSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item> e) {
	}
}

/// <summary>
/// Group and describe related tasks that you or your team needs to complete.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Summary Task", Id="0x012004", List="Workflow Tasks")]
public partial class WorkflowTasksSummaryTask : SummaryTask {
	
	private Microsoft.SharePoint.Linq.EntitySet<Item> _predecessors;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public WorkflowTasksSummaryTask() {
		this._predecessors = new Microsoft.SharePoint.Linq.EntitySet<Item>();
		this._predecessors.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item>>(this.OnPredecessorsSync);
		this._predecessors.OnChanged += new System.EventHandler(this.OnPredecessorsChanged);
		this._predecessors.OnChanging += new System.EventHandler(this.OnPredecessorsChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DueDate", Storage="_dueDate", FieldType="DateTime")]
	public override System.Nullable<System.DateTime> DueDate {
		get {
			return this._dueDate;
		}
		set {
			if ((value != this._dueDate)) {
				this.OnPropertyChanging("DueDate", this._dueDate);
				this._dueDate = value;
				this.OnPropertyChanged("DueDate");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Status", Storage="_taskStatus", FieldType="Choice")]
	public override System.Nullable<TaskStatus> TaskStatus {
		get {
			return this._taskStatus;
		}
		set {
			if ((value != this._taskStatus)) {
				this.OnPropertyChanging("TaskStatus", this._taskStatus);
				this._taskStatus = value;
				this.OnPropertyChanged("TaskStatus");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Predecessors", Storage="_predecessors", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Multi, List="Workflow Tasks")]
	public Microsoft.SharePoint.Linq.EntitySet<Item> Predecessors {
		get {
			return this._predecessors;
		}
		set {
			this._predecessors.Assign(value);
		}
	}
	
	private void OnPredecessorsChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Predecessors", this._predecessors.Clone());
	}
	
	private void OnPredecessorsChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Predecessors");
	}
	
	private void OnPredecessorsSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item> e) {
	}
}

/// <summary>
/// Upload or link to a video.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Video", Id="0x0120D520", List="Images")]
public partial class ImagesVideo : DocumentSet {
	
	private string _previewImageURL;
	
	private System.Nullable<int> _frameWidth;
	
	private System.Nullable<int> _frameHeight;
	
	private System.Nullable<int> _lengthSeconds;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public ImagesVideo() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AlternateThumbnailUrl", Storage="_previewImageURL", FieldType="Url")]
	public string PreviewImageURL {
		get {
			return this._previewImageURL;
		}
		set {
			if ((value != this._previewImageURL)) {
				this.OnPropertyChanging("PreviewImageURL", this._previewImageURL);
				this._previewImageURL = value;
				this.OnPropertyChanged("PreviewImageURL");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="VideoWidthInPixels", Storage="_frameWidth", FieldType="Integer")]
	public System.Nullable<int> FrameWidth {
		get {
			return this._frameWidth;
		}
		set {
			if ((value != this._frameWidth)) {
				this.OnPropertyChanging("FrameWidth", this._frameWidth);
				this._frameWidth = value;
				this.OnPropertyChanged("FrameWidth");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="VideoHeightInPixels", Storage="_frameHeight", FieldType="Integer")]
	public System.Nullable<int> FrameHeight {
		get {
			return this._frameHeight;
		}
		set {
			if ((value != this._frameHeight)) {
				this.OnPropertyChanging("FrameHeight", this._frameHeight);
				this._frameHeight = value;
				this.OnPropertyChanged("FrameHeight");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="MediaLengthInSeconds", Storage="_lengthSeconds", FieldType="Integer")]
	public System.Nullable<int> LengthSeconds {
		get {
			return this._lengthSeconds;
		}
		set {
			if ((value != this._lengthSeconds)) {
				this.OnPropertyChanging("LengthSeconds", this._lengthSeconds);
				this._lengthSeconds = value;
				this.OnPropertyChanged("LengthSeconds");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Name {
		get {
			throw new System.InvalidOperationException("Field FileLeafRef was removed from content type Video.");
		}
		set {
			throw new System.InvalidOperationException("Field FileLeafRef was removed from content type Video.");
		}
	}
	
	/// <summary>
	/// A description of the Document Set
	/// </summary>
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Description {
		get {
			throw new System.InvalidOperationException("Field DocumentSetDescription was removed from content type Video.");
		}
		set {
			throw new System.InvalidOperationException("Field DocumentSetDescription was removed from content type Video.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override System.Nullable<int> ItemChildCountId {
		get {
			throw new System.InvalidOperationException("Field ItemChildCount was removed from content type Video.");
		}
		set {
			throw new System.InvalidOperationException("Field ItemChildCount was removed from content type Video.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string ItemChildCountItemChildCount {
		get {
			throw new System.InvalidOperationException("Field ItemChildCount was removed from content type Video.");
		}
		set {
			throw new System.InvalidOperationException("Field ItemChildCount was removed from content type Video.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override System.Nullable<int> FolderChildCountId {
		get {
			throw new System.InvalidOperationException("Field FolderChildCount was removed from content type Video.");
		}
		set {
			throw new System.InvalidOperationException("Field FolderChildCount was removed from content type Video.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string FolderChildCountFolderChildCount {
		get {
			throw new System.InvalidOperationException("Field FolderChildCount was removed from content type Video.");
		}
		set {
			throw new System.InvalidOperationException("Field FolderChildCount was removed from content type Video.");
		}
	}
}

/// <summary>
/// Upload or link to a video.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Video", Id="0x0120D520", List="Site Collection Images")]
public partial class SiteCollectionImagesVideo : DocumentSet {
	
	private string _previewImageURL;
	
	private System.Nullable<int> _frameWidth;
	
	private System.Nullable<int> _frameHeight;
	
	private System.Nullable<int> _lengthSeconds;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public SiteCollectionImagesVideo() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AlternateThumbnailUrl", Storage="_previewImageURL", FieldType="Url")]
	public string PreviewImageURL {
		get {
			return this._previewImageURL;
		}
		set {
			if ((value != this._previewImageURL)) {
				this.OnPropertyChanging("PreviewImageURL", this._previewImageURL);
				this._previewImageURL = value;
				this.OnPropertyChanged("PreviewImageURL");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="VideoWidthInPixels", Storage="_frameWidth", FieldType="Integer")]
	public System.Nullable<int> FrameWidth {
		get {
			return this._frameWidth;
		}
		set {
			if ((value != this._frameWidth)) {
				this.OnPropertyChanging("FrameWidth", this._frameWidth);
				this._frameWidth = value;
				this.OnPropertyChanged("FrameWidth");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="VideoHeightInPixels", Storage="_frameHeight", FieldType="Integer")]
	public System.Nullable<int> FrameHeight {
		get {
			return this._frameHeight;
		}
		set {
			if ((value != this._frameHeight)) {
				this.OnPropertyChanging("FrameHeight", this._frameHeight);
				this._frameHeight = value;
				this.OnPropertyChanged("FrameHeight");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="MediaLengthInSeconds", Storage="_lengthSeconds", FieldType="Integer")]
	public System.Nullable<int> LengthSeconds {
		get {
			return this._lengthSeconds;
		}
		set {
			if ((value != this._lengthSeconds)) {
				this.OnPropertyChanging("LengthSeconds", this._lengthSeconds);
				this._lengthSeconds = value;
				this.OnPropertyChanged("LengthSeconds");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Name {
		get {
			throw new System.InvalidOperationException("Field FileLeafRef was removed from content type Video.");
		}
		set {
			throw new System.InvalidOperationException("Field FileLeafRef was removed from content type Video.");
		}
	}
	
	/// <summary>
	/// A description of the Document Set
	/// </summary>
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Description {
		get {
			throw new System.InvalidOperationException("Field DocumentSetDescription was removed from content type Video.");
		}
		set {
			throw new System.InvalidOperationException("Field DocumentSetDescription was removed from content type Video.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override System.Nullable<int> ItemChildCountId {
		get {
			throw new System.InvalidOperationException("Field ItemChildCount was removed from content type Video.");
		}
		set {
			throw new System.InvalidOperationException("Field ItemChildCount was removed from content type Video.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string ItemChildCountItemChildCount {
		get {
			throw new System.InvalidOperationException("Field ItemChildCount was removed from content type Video.");
		}
		set {
			throw new System.InvalidOperationException("Field ItemChildCount was removed from content type Video.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override System.Nullable<int> FolderChildCountId {
		get {
			throw new System.InvalidOperationException("Field FolderChildCount was removed from content type Video.");
		}
		set {
			throw new System.InvalidOperationException("Field FolderChildCount was removed from content type Video.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string FolderChildCountFolderChildCount {
		get {
			throw new System.InvalidOperationException("Field FolderChildCount was removed from content type Video.");
		}
		set {
			throw new System.InvalidOperationException("Field FolderChildCount was removed from content type Video.");
		}
	}
}

[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="ListFieldsContentType", Id="0x01", List="Movies")]
public partial class MoviesListFieldsContentType : Item {
	
	private string _yearReleased;
	
	private System.Nullable<MovieGenre> _movieGenre;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public MoviesListFieldsContentType() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Released", Storage="_yearReleased", FieldType="Text")]
	public string YearReleased {
		get {
			return this._yearReleased;
		}
		set {
			if ((value != this._yearReleased)) {
				this.OnPropertyChanging("YearReleased", this._yearReleased);
				this._yearReleased = value;
				this.OnPropertyChanged("YearReleased");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Genre", Storage="_movieGenre", FieldType="Choice")]
	public System.Nullable<MovieGenre> MovieGenre {
		get {
			return this._movieGenre;
		}
		set {
			if ((value != this._movieGenre)) {
				this.OnPropertyChanging("MovieGenre", this._movieGenre);
				this._movieGenre = value;
				this.OnPropertyChanged("MovieGenre");
			}
		}
	}
}

/// <summary>
/// Upload an image.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Image", Id="0x0101009148F5A04DDD49CBA7127AADA5FB792B00AADE34325A8B49CDA8BB4DB53328F214")]
public partial class Image : RichMediaAsset {
	
	private string _pictureSize;
	
	private System.Nullable<int> _pictureHeight;
	
	private string _comments;
	
	private string _author;
	
	private System.Nullable<System.DateTime> _datePictureTaken;
	
	private string _copyright;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Image() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ImageSize", Storage="_pictureSize", FieldType="Computed")]
	public string PictureSize {
		get {
			return this._pictureSize;
		}
		set {
			if ((value != this._pictureSize)) {
				this.OnPropertyChanging("PictureSize", this._pictureSize);
				this._pictureSize = value;
				this.OnPropertyChanged("PictureSize");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ImageHeight", Storage="_pictureHeight", ReadOnly=true, FieldType="Integer")]
	public System.Nullable<int> PictureHeight {
		get {
			return this._pictureHeight;
		}
		set {
			if ((value != this._pictureHeight)) {
				this.OnPropertyChanging("PictureHeight", this._pictureHeight);
				this._pictureHeight = value;
				this.OnPropertyChanged("PictureHeight");
			}
		}
	}
	
	/// <summary>
	/// A summary of this resource
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_Comments", Storage="_comments", FieldType="Note")]
	public string Comments {
		get {
			return this._comments;
		}
		set {
			if ((value != this._comments)) {
				this.OnPropertyChanging("Comments", this._comments);
				this._comments = value;
				this.OnPropertyChanged("Comments");
			}
		}
	}
	
	/// <summary>
	/// The primary author
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_Author", Storage="_author", FieldType="Text")]
	public string Author {
		get {
			return this._author;
		}
		set {
			if ((value != this._author)) {
				this.OnPropertyChanging("Author", this._author);
				this._author = value;
				this.OnPropertyChanged("Author");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ImageCreateDate", Storage="_datePictureTaken", FieldType="DateTime")]
	public System.Nullable<System.DateTime> DatePictureTaken {
		get {
			return this._datePictureTaken;
		}
		set {
			if ((value != this._datePictureTaken)) {
				this.OnPropertyChanging("DatePictureTaken", this._datePictureTaken);
				this._datePictureTaken = value;
				this.OnPropertyChanged("DatePictureTaken");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="wic_System_Copyright", Storage="_copyright", FieldType="Text")]
	public string Copyright {
		get {
			return this._copyright;
		}
		set {
			if ((value != this._copyright)) {
				this.OnPropertyChanging("Copyright", this._copyright);
				this._copyright = value;
				this.OnPropertyChanged("Copyright");
			}
		}
	}
}

/// <summary>
/// Upload an audio file.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Audio", Id="0x0101009148F5A04DDD49CBA7127AADA5FB792B006973ACD696DC4858A76371B2FB2F439A")]
public partial class Audio : RichMediaAsset {
	
	private string _author;
	
	private string _comments;
	
	private string _previewImageURL;
	
	private string _copyright;
	
	private System.Nullable<int> _lengthSeconds;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Audio() {
		this.OnCreated();
	}
	
	/// <summary>
	/// The primary author
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_Author", Storage="_author", FieldType="Text")]
	public string Author {
		get {
			return this._author;
		}
		set {
			if ((value != this._author)) {
				this.OnPropertyChanging("Author", this._author);
				this._author = value;
				this.OnPropertyChanged("Author");
			}
		}
	}
	
	/// <summary>
	/// A summary of this resource
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_Comments", Storage="_comments", FieldType="Note")]
	public string Comments {
		get {
			return this._comments;
		}
		set {
			if ((value != this._comments)) {
				this.OnPropertyChanging("Comments", this._comments);
				this._comments = value;
				this.OnPropertyChanged("Comments");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AlternateThumbnailUrl", Storage="_previewImageURL", FieldType="Url")]
	public string PreviewImageURL {
		get {
			return this._previewImageURL;
		}
		set {
			if ((value != this._previewImageURL)) {
				this.OnPropertyChanging("PreviewImageURL", this._previewImageURL);
				this._previewImageURL = value;
				this.OnPropertyChanged("PreviewImageURL");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="wic_System_Copyright", Storage="_copyright", FieldType="Text")]
	public string Copyright {
		get {
			return this._copyright;
		}
		set {
			if ((value != this._copyright)) {
				this.OnPropertyChanging("Copyright", this._copyright);
				this._copyright = value;
				this.OnPropertyChanged("Copyright");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="MediaLengthInSeconds", Storage="_lengthSeconds", FieldType="Integer")]
	public System.Nullable<int> LengthSeconds {
		get {
			return this._lengthSeconds;
		}
		set {
			if ((value != this._lengthSeconds)) {
				this.OnPropertyChanging("LengthSeconds", this._lengthSeconds);
				this._lengthSeconds = value;
				this.OnPropertyChanged("LengthSeconds");
			}
		}
	}
}

/// <summary>
/// Upload a video file.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Video Rendition", Id="0x0101009148F5A04DDD49CBA7127AADA5FB792B00291D173ECE694D56B19D111489C4369D")]
public partial class VideoRendition : RichMediaAsset {
	
	private string _author;
	
	private string _comments;
	
	private string _previewImageURL;
	
	private string _copyright;
	
	private System.Nullable<int> _lengthSeconds;
	
	private System.Nullable<int> _frameWidth;
	
	private System.Nullable<int> _frameHeight;
	
	private string _label;
	
	private System.Nullable<int> _bitRate;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public VideoRendition() {
		this.OnCreated();
	}
	
	/// <summary>
	/// The primary author
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_Author", Storage="_author", FieldType="Text")]
	public string Author {
		get {
			return this._author;
		}
		set {
			if ((value != this._author)) {
				this.OnPropertyChanging("Author", this._author);
				this._author = value;
				this.OnPropertyChanged("Author");
			}
		}
	}
	
	/// <summary>
	/// A summary of this resource
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_Comments", Storage="_comments", FieldType="Note")]
	public string Comments {
		get {
			return this._comments;
		}
		set {
			if ((value != this._comments)) {
				this.OnPropertyChanging("Comments", this._comments);
				this._comments = value;
				this.OnPropertyChanged("Comments");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AlternateThumbnailUrl", Storage="_previewImageURL", FieldType="Url")]
	public string PreviewImageURL {
		get {
			return this._previewImageURL;
		}
		set {
			if ((value != this._previewImageURL)) {
				this.OnPropertyChanging("PreviewImageURL", this._previewImageURL);
				this._previewImageURL = value;
				this.OnPropertyChanged("PreviewImageURL");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="wic_System_Copyright", Storage="_copyright", FieldType="Text")]
	public string Copyright {
		get {
			return this._copyright;
		}
		set {
			if ((value != this._copyright)) {
				this.OnPropertyChanging("Copyright", this._copyright);
				this._copyright = value;
				this.OnPropertyChanged("Copyright");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="MediaLengthInSeconds", Storage="_lengthSeconds", FieldType="Integer")]
	public System.Nullable<int> LengthSeconds {
		get {
			return this._lengthSeconds;
		}
		set {
			if ((value != this._lengthSeconds)) {
				this.OnPropertyChanging("LengthSeconds", this._lengthSeconds);
				this._lengthSeconds = value;
				this.OnPropertyChanged("LengthSeconds");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="VideoWidthInPixels", Storage="_frameWidth", FieldType="Integer")]
	public System.Nullable<int> FrameWidth {
		get {
			return this._frameWidth;
		}
		set {
			if ((value != this._frameWidth)) {
				this.OnPropertyChanging("FrameWidth", this._frameWidth);
				this._frameWidth = value;
				this.OnPropertyChanged("FrameWidth");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="VideoHeightInPixels", Storage="_frameHeight", FieldType="Integer")]
	public System.Nullable<int> FrameHeight {
		get {
			return this._frameHeight;
		}
		set {
			if ((value != this._frameHeight)) {
				this.OnPropertyChanging("FrameHeight", this._frameHeight);
				this._frameHeight = value;
				this.OnPropertyChanged("FrameHeight");
			}
		}
	}
	
	/// <summary>
	/// The text displayed in the video player for this rendition
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="VideoRenditionLabel", Storage="_label", FieldType="Text")]
	public string Label {
		get {
			return this._label;
		}
		set {
			if ((value != this._label)) {
				this.OnPropertyChanging("Label", this._label);
				this._label = value;
				this.OnPropertyChanged("Label");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="VideoRenditionBitRate", Storage="_bitRate", FieldType="Integer")]
	public System.Nullable<int> BitRate {
		get {
			return this._bitRate;
		}
		set {
			if ((value != this._bitRate)) {
				this.OnPropertyChanging("BitRate", this._bitRate);
				this._bitRate = value;
				this.OnPropertyChanged("BitRate");
			}
		}
	}
}

/// <summary>
/// Page is a system content type template created by the Publishing Resources feature. The column templates from Page will be added to all Pages libraries created by the Publishing feature.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Page", Id="0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF39")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(EnterpriseWikiPage))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(RedirectPage))]
public partial class Page : SystemPage {
	
	private string _browserTitle;
	
	private string _metaDescription;
	
	private string _metaKeywords;
	
	private System.Nullable<bool> _hideFromInternetSearchEngines;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Page() {
		this.OnCreated();
	}
	
	/// <summary>
	/// Browser Title is a site column created by the Publishing feature. It is used as the title that appears at the top of a browser window and may appear in Internet search results.
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="SeoBrowserTitle", Storage="_browserTitle", FieldType="Text")]
	public string BrowserTitle {
		get {
			return this._browserTitle;
		}
		set {
			if ((value != this._browserTitle)) {
				this.OnPropertyChanging("BrowserTitle", this._browserTitle);
				this._browserTitle = value;
				this.OnPropertyChanged("BrowserTitle");
			}
		}
	}
	
	/// <summary>
	/// Meta Description is a site column created by the Publishing feature. Internet search engines may display this description in search results pages.
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="SeoMetaDescription", Storage="_metaDescription", FieldType="Text")]
	public string MetaDescription {
		get {
			return this._metaDescription;
		}
		set {
			if ((value != this._metaDescription)) {
				this.OnPropertyChanging("MetaDescription", this._metaDescription);
				this._metaDescription = value;
				this.OnPropertyChanged("MetaDescription");
			}
		}
	}
	
	/// <summary>
	/// Meta Keywords
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="SeoKeywords", Storage="_metaKeywords", FieldType="Text")]
	public string MetaKeywords {
		get {
			return this._metaKeywords;
		}
		set {
			if ((value != this._metaKeywords)) {
				this.OnPropertyChanging("MetaKeywords", this._metaKeywords);
				this._metaKeywords = value;
				this.OnPropertyChanged("MetaKeywords");
			}
		}
	}
	
	/// <summary>
	/// Hide from Internet Search Engines is a site column created by the Publishing feature. It is used to indicate to search engine crawlers that a particular page should not be indexed.
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="RobotsNoIndex", Storage="_hideFromInternetSearchEngines", FieldType="Boolean")]
	public System.Nullable<bool> HideFromInternetSearchEngines {
		get {
			return this._hideFromInternetSearchEngines;
		}
		set {
			if ((value != this._hideFromInternetSearchEngines)) {
				this.OnPropertyChanging("HideFromInternetSearchEngines", this._hideFromInternetSearchEngines);
				this._hideFromInternetSearchEngines = value;
				this.OnPropertyChanged("HideFromInternetSearchEngines");
			}
		}
	}
}

/// <summary>
/// Enterprise Wiki Page is the default content type for the Enterprise Wiki site template. Provides a basic content area as well as ratings and categories.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Enterprise Wiki Page", Id="0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF39004C1F8" +
	"B46085B4D22B1CDC3DE08CFFB9C")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(ProjectPage))]
public partial class EnterpriseWikiPage : Page {
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public EnterpriseWikiPage() {
		this.OnCreated();
	}
}

/// <summary>
/// Redirect Page is a system content type template created by the Publishing Resources feature. It is the associated content type template for the redirect page layout
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Redirect Page", Id="0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF3900FD0E8" +
	"70BA06948879DBD5F9813CD8799")]
public partial class RedirectPage : Page {
	
	private string _redirectURL;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public RedirectPage() {
		this.OnCreated();
	}
	
	/// <summary>
	/// Redirect URL is a site column created by the Publishing feature. It is used on the Redirect Page Content Type as the web address that the page will redirect to.
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="RedirectURL", Storage="_redirectURL", FieldType="Url")]
	public string RedirectURL {
		get {
			return this._redirectURL;
		}
		set {
			if ((value != this._redirectURL)) {
				this.OnPropertyChanging("RedirectURL", this._redirectURL);
				this._redirectURL = value;
				this.OnPropertyChanged("RedirectURL");
			}
		}
	}
}

/// <summary>
/// Project Page is a content type included with the Enterprise Wiki site template. Provides some basic information to describe a project including a project status and a contact name.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Project Page", Id="0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF39004C1F8" +
	"B46085B4D22B1CDC3DE08CFFB9C0055EF50AAFF2E4BADA437E4BAE09A30F8")]
public partial class ProjectPage : EnterpriseWikiPage {
	
	private string _webPage;
	
	private System.Nullable<TaskStatus> _taskStatus;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public ProjectPage() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WebPage", Storage="_webPage", FieldType="Url")]
	public string WebPage {
		get {
			return this._webPage;
		}
		set {
			if ((value != this._webPage)) {
				this.OnPropertyChanging("WebPage", this._webPage);
				this._webPage = value;
				this.OnPropertyChanged("WebPage");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="TaskStatus", Storage="_taskStatus", FieldType="Choice")]
	public System.Nullable<TaskStatus> TaskStatus {
		get {
			return this._taskStatus;
		}
		set {
			if ((value != this._taskStatus)) {
				this.OnPropertyChanging("TaskStatus", this._taskStatus);
				this._taskStatus = value;
				this.OnPropertyChanged("TaskStatus");
			}
		}
	}
}

public enum Priority : int {
	
	None = 0,
	
	Invalid = 1,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(1) High")]
	_1High = 2,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(2) Normal")]
	_2Normal = 4,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(3) Low")]
	_3Low = 8,
}

public enum TaskStatus : int {
	
	None = 0,
	
	Invalid = 1,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Not Started")]
	NotStarted = 2,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="In Progress")]
	InProgress = 4,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Completed")]
	Completed = 8,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Deferred")]
	Deferred = 16,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Waiting on someone else")]
	WaitingOnSomeoneElse = 32,
}

public enum ContentCategory : int {
	
	None = 0,
	
	Invalid = 1,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="None")]
	None0 = 2,
}

public enum MovieGenre : int {
	
	None = 0,
	
	Invalid = 1,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Action")]
	Action = 2,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Comedy")]
	Comedy = 4,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Drama")]
	Drama = 8,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Musical")]
	Musical = 16,
}
